// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
//FirebaseOptions Firebase = FirebaseOptions(apiKey: apiKey, appId: appId, messagingSenderId: messagingSenderId, projectId: projectId)
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDycN1vGBkhJiARqY2CL3SZJyQ_qc4evek',
    appId: '1:1015602209336:web:7b80e87b28a8813246bccd',
    messagingSenderId: '1015602209336',
    projectId: 'fire-8b747',
    authDomain: 'fire-8b747.firebaseapp.com',
    storageBucket: 'fire-8b747.appspot.com',
    measurementId: 'G-7HJP7Q0D0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg8HAqnjqVidRc1WuZgDUHGTcw_fJK6mA',
    appId: '1:1015602209336:android:6f4be71b4ab3b9b646bccd',
    messagingSenderId: '1015602209336',
    projectId: 'fire-8b747',
    storageBucket: 'fire-8b747.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6qvowN1imew4xYdKtusrQ0H1QYndOEX4',
    appId: '1:1015602209336:ios:0b2ca28d4e3e8c8f46bccd',
    messagingSenderId: '1015602209336',
    projectId: 'fire-8b747',
    storageBucket: 'fire-8b747.appspot.com',
    iosClientId: '1015602209336-k12c16k8h7ecvbh1l3ghm1ktngv42s01.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginapp',
  );
}
